import { FifthLabEvent, Lead, FifthLabProduct, ProductOwner, DashboardKPI } from "./types";

export const MOCK_PRODUCT_OWNERS: ProductOwner[] = [
  {
    id: "po-1",
    name: "Olumide Adebayo",
    role: "VP of Product - FifthLab Payments",
    email: "olumide.adebayo@fifthlab.ng",
    timezone: "WAT (UTC+1) - West Africa Time",
    workingHours: "08:00 - 17:00 WAT",
    assignedProducts: ["FifthLab PayNaira", "Nexus POS Terminal"],
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "po-2",
    name: "Chioma Chukwu",
    role: "Head of Identity & Compliance Engine",
    email: "chioma.chukwu@fifthlab.ng",
    timezone: "WAT (UTC+1) - West Africa Time",
    workingHours: "08:30 - 16:30 WAT",
    assignedProducts: ["FifthLab Identity Verification", "NIN & BVN Proofing"],
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "po-3",
    name: "Babatunde Ojo",
    role: "Lead Architect - CWG PLC Energy Systems",
    email: "babatunde.ojo@cwgplc.com",
    timezone: "WAT (UTC+1) - West Africa Time",
    workingHours: "09:00 - 18:00 WAT",
    assignedProducts: ["CWG Energy Automation OS", "FifthLab Real-Time Analytics"],
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "po-4",
    name: "Amina Yusuf",
    role: "Director of Enterprise Banking Architecture",
    email: "amina.yusuf@fifthlab.ng",
    timezone: "WAT (UTC+1) - West Africa Time",
    workingHours: "08:00 - 17:00 WAT",
    assignedProducts: ["FifthLab Core Banking Engine", "CWG Industrial Monitoring"],
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop",
  },
];

export const MOCK_PRODUCTS: FifthLabProduct[] = [
  {
    id: "prod-paynaira",
    name: "FifthLab PayNaira",
    tagline: "Sub-second instant NIBSS & local card switch routing",
    description: "Enterprise payment gateway supporting instant NGN transfers, USSD, and high-velocity retail transaction switching.",
    ownerId: "po-1",
    ownerName: "Olumide Adebayo",
    iconName: "CreditCard",
    activeDemosThisMonth: 42,
    availableSlots: ["09:00 AM", "11:30 AM", "02:00 PM", "04:30 PM"],
  },
  {
    id: "prod-identity",
    name: "FifthLab Identity & BVN Sync",
    tagline: "Cryptographic identity verification & automated NIN lookup",
    description: "Instant KYC, biometric proofing, and CBN-compliant identity layer for Nigerian financial institutions.",
    ownerId: "po-2",
    ownerName: "Chioma Chukwu",
    iconName: "ShieldCheck",
    activeDemosThisMonth: 31,
    availableSlots: ["10:00 AM", "01:00 PM", "03:30 PM"],
  },
  {
    id: "prod-cwp-energy",
    name: "CWG Energy Automation OS",
    tagline: "Industrial grid metering & real-time telemetry",
    description: "Enterprise IoT and grid management platform developed by CWG PLC for large industrial infrastructure.",
    ownerId: "po-3",
    ownerName: "Babatunde Ojo",
    iconName: "BarChart3",
    activeDemosThisMonth: 18,
    availableSlots: ["09:30 AM", "12:00 PM", "02:30 PM", "05:00 PM"],
  },
  {
    id: "prod-banking-core",
    name: "FifthLab Core Banking Engine",
    tagline: "Micro-ledger architecture for commercial & MFB banks",
    description: "High-concurrency banking ledger with automated ledger balancing, loan management, and CBN compliance reporting.",
    ownerId: "po-4",
    ownerName: "Amina Yusuf",
    iconName: "FileCheck2",
    activeDemosThisMonth: 29,
    availableSlots: ["11:00 AM", "01:30 PM", "04:00 PM"],
  },
];

export const MOCK_EVENTS: FifthLabEvent[] = [
  {
    id: "evt-101",
    title: "Lagos Tech Fest 2026",
    category: "Summit",
    priority: "High",
    date: "2026-08-14",
    time: "09:00 AM - 06:00 PM WAT",
    location: "Landmark Centre, Victoria Island",
    city: "Lagos",
    country: "Nigeria",
    description: "Nigeria's flagship tech gathering uniting bank executives, fintech founders, and CWG PLC technology leaders.",
    strategicNotes: "Pitch FifthLab PayNaira sub-second settlement engine to Tier-1 Nigerian commercial banks.",
    boothNumber: "Main Hall - Stand A-12",
    expectedAttendance: 8500,
    confirmedStaffCount: 4,
    isFifthLabAttending: true,
    attendanceManifest: [
      { userId: "u-1", userName: "Olumide Adebayo", userRole: "VP of Product", avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop", confirmedAt: "2026-07-28 14:22", status: "Attending" },
      { userId: "u-2", userName: "Chioma Chukwu", userRole: "Head of Identity", avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=150&auto=format&fit=crop", confirmedAt: "2026-07-29 09:10", status: "Attending" },
      { userId: "u-3", userName: "Babatunde Ojo", userRole: "CWG Lead Architect", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop", confirmedAt: "2026-07-29 11:45", status: "Attending" },
      { userId: "u-4", userName: "Amina Yusuf", userRole: "Banking Director", avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=150&auto=format&fit=crop", confirmedAt: "2026-07-30 08:30", status: "Attending" }
    ],
  },
  {
    id: "evt-102",
    title: "Techpoint Africa Executive Summit",
    category: "Exposition",
    priority: "High",
    date: "2026-08-28",
    time: "08:30 AM - 05:00 PM WAT",
    location: "Zone Tech Park, Gbagada",
    city: "Lagos",
    country: "Nigeria",
    description: "Annual pan-African enterprise technology showcase highlighting cloud infrastructure, local switching, and energy automation.",
    strategicNotes: "Joint executive panel with CWG PLC on industrial IoT and payments infrastructure in West Africa.",
    boothNumber: "Innovation Bay - Booth 4",
    expectedAttendance: 12000,
    confirmedStaffCount: 3,
    isFifthLabAttending: true,
    attendanceManifest: [
      { userId: "u-1", userName: "Olumide Adebayo", userRole: "VP of Product", avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop", confirmedAt: "2026-07-25 16:20", status: "Attending" },
      { userId: "u-3", userName: "Babatunde Ojo", userRole: "CWG Lead Architect", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop", confirmedAt: "2026-07-26 10:15", status: "Attending" },
      { userId: "u-4", userName: "Amina Yusuf", userRole: "Banking Director", avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=150&auto=format&fit=crop", confirmedAt: "2026-07-27 13:00", status: "Attending" }
    ],
  },
  {
    id: "evt-103",
    title: "CWG PLC Industrial & Energy Expo",
    category: "Executive Briefing",
    priority: "High",
    date: "2026-09-05",
    time: "10:00 AM - 04:00 PM WAT",
    location: "Transcorp Hilton",
    city: "Abuja",
    country: "Nigeria",
    description: "Exclusive corporate gathering hosted by CWG PLC focusing on energy metering, power distribution analytics, and enterprise OS deployment.",
    strategicNotes: "Babatunde Ojo delivering keynote on 'CWG Energy Automation OS in National Infrastructure'.",
    expectedAttendance: 500,
    confirmedStaffCount: 2,
    isFifthLabAttending: true,
    attendanceManifest: [
      { userId: "u-3", userName: "Babatunde Ojo", userRole: "CWG Lead Architect", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop", confirmedAt: "2026-07-20 18:00", status: "Attending" },
      { userId: "u-4", userName: "Amina Yusuf", userRole: "Banking Director", avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=150&auto=format&fit=crop", confirmedAt: "2026-07-22 09:40", status: "Attending" }
    ],
  },
  {
    id: "evt-104",
    title: "FifthLab Fintech Africa Conference",
    category: "Conference",
    priority: "Medium",
    date: "2026-09-18",
    time: "09:00 AM - 05:30 PM WAT",
    location: "Eko Hotels & Suites, Victoria Island",
    city: "Lagos",
    country: "Nigeria",
    description: "Premier West African fintech summit bringing together regulatory leads from CBN, NIBSS, and enterprise banking partners.",
    strategicNotes: "Demonstrate FifthLab Identity & BVN verification engine to compliance officers.",
    expectedAttendance: 6000,
    confirmedStaffCount: 2,
    isFifthLabAttending: true,
    attendanceManifest: [
      { userId: "u-2", userName: "Chioma Chukwu", userRole: "Head of Identity", avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=150&auto=format&fit=crop", confirmedAt: "2026-07-24 10:00", status: "Attending" }
    ],
  },
  {
    id: "evt-105",
    title: "Nigeria International Tech Exposition",
    category: "Exposition",
    priority: "Low",
    date: "2026-10-02",
    time: "09:00 AM - 06:00 PM WAT",
    location: "International Conference Centre (ICC)",
    city: "Abuja",
    country: "Nigeria",
    description: "Federal technology exposition highlighting public sector digital transformational tools and CWG PLC infrastructure projects.",
    strategicNotes: "Examine federal procurement opportunities for FifthLab Core Banking and CWG Energy OS.",
    expectedAttendance: 10000,
    confirmedStaffCount: 0,
    isFifthLabAttending: false,
    attendanceManifest: [],
  }
];

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-901",
    visitorName: "Gbenga Olufemi",
    company: "Flutterwave Nigeria",
    email: "gbenga.o@flutterwave.com",
    phone: "+234 803 123 4567",
    productInterested: "FifthLab PayNaira",
    assignedProductOwner: "Olumide Adebayo",
    bookingDate: "2026-08-04",
    bookingTime: "11:30 AM",
    status: "Unread",
    notes: "Requesting sub-second settlement routing and backup NIBSS switch failover tests.",
    createdAt: "2026-07-30 21:14",
  },
  {
    id: "lead-902",
    visitorName: "Folake Balogun",
    company: "Paystack Technologies",
    email: "folake.b@paystack.com",
    phone: "+234 802 987 6543",
    productInterested: "FifthLab Identity & BVN Sync",
    assignedProductOwner: "Chioma Chukwu",
    bookingDate: "2026-08-05",
    bookingTime: "01:00 PM",
    status: "Followed Up",
    notes: "Requires automated NIN & BVN verification API for tier-3 merchant onboarding.",
    createdAt: "2026-07-30 19:40",
  },
  {
    id: "lead-903",
    visitorName: "Emeka Okafor",
    company: "GTBank Enterprise Systems",
    email: "emeka.okafor@gtbank.com",
    phone: "+234 805 444 3322",
    productInterested: "FifthLab Core Banking Engine",
    assignedProductOwner: "Amina Yusuf",
    bookingDate: "2026-08-06",
    bookingTime: "02:30 PM",
    status: "Qualified",
    notes: "Evaluating micro-ledger transaction scalability for high-frequency retail transfers.",
    createdAt: "2026-07-30 15:10",
  },
  {
    id: "lead-904",
    visitorName: "Amara Nwosu",
    company: "Kuda Microfinance Bank",
    email: "anwosu@kudabank.com",
    phone: "+234 802 345 6789",
    productInterested: "FifthLab PayNaira",
    assignedProductOwner: "Olumide Adebayo",
    bookingDate: "2026-08-07",
    bookingTime: "09:00 AM",
    status: "Converted",
    notes: "Contract finalized. Preparing staging test suite for NGN card & transfer switching.",
    createdAt: "2026-07-29 11:20",
  },
  {
    id: "lead-905",
    visitorName: "Tunde Ednut",
    company: "CWG PLC Energy Operations",
    email: "tunde.ednut@cwpplc.com",
    phone: "+234 807 111 2233",
    productInterested: "CWG Energy Automation OS",
    assignedProductOwner: "Babatunde Ojo",
    bookingDate: "2026-08-08",
    bookingTime: "11:00 AM",
    status: "Unread",
    notes: "Industrial meter telemetry deployment for new industrial facility in Ikeja.",
    createdAt: "2026-07-29 08:45",
  },
  {
    id: "lead-906",
    visitorName: "Zainab Ahmed",
    company: "Interswitch Group",
    email: "zainab.ahmed@interswitch.com",
    phone: "+234 809 999 8877",
    productInterested: "FifthLab PayNaira",
    assignedProductOwner: "Olumide Adebayo",
    bookingDate: "2026-08-10",
    bookingTime: "02:00 PM",
    status: "Followed Up",
    notes: "Switching inter-operability test for regional POS terminal routing.",
    createdAt: "2026-07-28 17:05",
  }
];

export const MOCK_KPI: DashboardKPI = {
  upcomingEventsCount: 18,
  demoRequestsThisMonth: 63,
  conversionRate: "41.2%",
  activeProductOwners: 4,
};
